/**
 * We currently install a pug fork that implements these pull requests:
 * https://github.com/pugjs/pug/pull/3346
 * https://github.com/pugjs/pug/pull/3413
 *
 * Because of this, we need to specify all the pug dependencies as externals,
 * so that they don't get bundled with the final build.
 */
const pugExternals = [
  'pug',
  'pug-lexer',
  'pug-strip-comments',
  'pug-parser',
  'pug-load',
  'pug-filters',
  'pug-linker',
  'pug-code-gen',
  'pug-runtime',
  'pug-runtime/wrap',
  'token-stream',
  'pug-error',
  'doctypes',
  'pug-runtime/build',
  'pug-attrs',
  'void-elements',
  'constantinople',
  'js-stringify',
  'with',
  'is-expression',
  'character-parser',
  'pug-walk',
  'object-assign',
  'jstransformer',
  'resolve',
  'is-regex',
  '@babel/parser',
  '@babel/types',
  'babel-walk',
  'acorn',
  'assert-never',
  'promise',
  'is-promise',
  'call-bound',
  'has-tostringtag/shams',
  'hasown',
  'gopd',
  'is-core-module',
  'function-bind',
  'get-intrinsic',
  'call-bind-apply-helpers',
  'has-symbols/shams',
  'path-parse',
  '@babel/helper-validator-identifier',
  'es-errors/type',
  'es-object-atoms',
  'es-errors',
  'es-errors/eval',
  'es-errors/range',
  'es-errors/ref',
  'es-errors/syntax',
  'es-errors/uri',
  'math-intrinsics/abs',
  'math-intrinsics/floor',
  'math-intrinsics/max',
  'math-intrinsics/min',
  'math-intrinsics/pow',
  'math-intrinsics/round',
  'math-intrinsics/sign',
  'es-define-property',
  'has-symbols',
  'get-proto',
  'get-proto/Object.getPrototypeOf',
  'get-proto/Reflect.getPrototypeOf',
  'call-bind-apply-helpers/functionApply',
  'call-bind-apply-helpers/functionCall',
  '@babel/helper-string-parser',
  'dunder-proto/get',
  'asap/raw',
  'asap',
]

export default {
  outDir: 'dist/node',
  entries: ['./lib/index', './lib/vite-pug/worker'],
  declaration: true,
  failOnWarn: false,
  externals: ['eslint', '@antfu/eslint-config', 'eslint-flat-config-utils', ...pugExternals],
}
