name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build dist files
        run: bun run build

      - name: Publish to npm
        run: |
          if [[ "${{ github.ref_name }}" == *beta* || "${{ github.ref_name }}" == *alpha* ]]; then
            echo "Publishing beta version..."
            bun publish --tag beta --access public
          else
            echo "Publishing stable version..."
            bun publish --access public
          fi
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
